### PR TITLE
Anusheh Profile View

### PR DESCRIPTION
**Pull request by anushehchaudry**
# Anusheh Chaudry

## :recycle: Current situation & Problem
Anusheh's profile view was missing.

## :bulb: Proposed solution
Add Anusheh's view

## :gear: Release Notes 
*Add a summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented if it appends or changes the public interface.*

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Related PRs
*Reference the related PRs*

### Testing
Added some UI tests

### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by vishnuravi** [comment]
Hey @anushehchaudry,

We're having trouble opening your project file - Xcode is complaining of a parsing error. Are you able to open it on your end? Let us know, and we can help you fix this.

cc: @PSchmiedmayer

**Review by vishnuravi — CHANGES_REQUESTED** [review]
Hey @anushehchaudry,

We're having trouble opening your project - Xcode is complaining of a parsing error in your project file. It seems that something may have gone wrong with the project file when you merged from the main branch. Are you able to open it on your end? Let us know, and we can help you fix this.

cc: @PSchmiedmayer

**Comment by PSchmiedmayer** [comment]
@anushehchaudry @vishnuravi I have taken a look at the merge issue in the Xcode project file and other Swift files. You can see the diff at: https://github.com/CS342/CS342-2023-Application/pull/23/commits/44ddca30168aed7d9ec5d0dcfcb37d8d13c66802 .
I have also merged the main branch in this feature branch so we can go on for a review and bring your nice view in the main branch.

@anushehchaudry Please be sure that you `git pull` before you make any further changes on your machine so you have the latest version of your feature branch.

**Review by vishnuravi — APPROVED** [review]
Thank you @PSchmiedmayer for your help!

Hey @anushehchaudry, you did a great job with this assignment! Your view looks great and love the photos!

There were some extraneous files in the Assets folder that I removed for you. There's also a merge conflict with the `main` branch now since other students have been merging in their assignments. Do you want to give a try resolving the merge conflicts? If you run into trouble, just let us know.

Thanks!
Vishnu

**Pull request merged**
