### PR TITLE
Feature/adam

### PR DESCRIPTION
**Pull request by ty-zhao1**
# Feature/adam

## :recycle: Current situation & Problem
Successfully fixed merge conflicts and passing all tests right now.

## :gear: Release Notes 
Added a view of myself to the application with some subviews, hyperlinks, and multiple images. Navigation stack seems to work cleanly, as well as hyperlinking.

## :heavy_plus_sign: Additional Information
*Provide some additional information if possible*

### Related PRs
*Reference the related PRs*

### Testing
I have tested all buttons and all navigation stack things. There may be (probably are) some bugs that I didn't catch, but I am fairly confident this will not explode at any point.

### Reviewer Nudging
Any advice to clean up Photography.swift would be appreciated. How should I approach it, with a class, struct, enum? I was just lost as to how to do it so I did it all manually.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ty-zhao1** [comment]
I finally fixed the merge issue, will address tests when I'm not so exhausted

**Comment by ty-zhao1** [comment]
I'm unsure of why the Build and Test iOS App thing is failing, because I'm passing all tests on my end and the application is building. Any advice would be appreciatd.

**Comment by ty-zhao1** [comment]
I'm not sure why the Build and Test iOS app is failing; it seems to build and run just fine on my laptop, and passes all the tests. Any tips would be greatly appreciated.

**Comment by ty-zhao1** [comment]
@vishnuravi could you help on the build and run test? Again it seems to be running fine locally. I feel like I'm looking in the wrong places and it's driving me crazy.

**Comment by PSchmiedmayer** [comment]
@ty-zhao1 Thank you for your PR. In the sprit of getting done with Assignment #1 and merging all PRs we have fixed the build error and will merge the PR for you. Thank you for your nice view! 👍

**Pull request merged**
