### PR TITLE
Feature/jenn

### PR DESCRIPTION
**Pull request by jennxu23**
# *Jennifer Xu View*

## :recycle: Current situation & Problem
*Describe the current situation (if possible, with an exemplary (or real) code snippet and/or where this is used)*
*Please link any open issue that is addressed with this PR*

I didn't have a page in the CS342 app.

## :bulb: Proposed solution
I added my personal page, which includes a picture of me, my social media links, a short bio, and a timeline of recent professional milestones.

## :gear: Release Notes 
*Add a summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented if it appends or changes the public interface.*

## :heavy_plus_sign: Additional Information
I used the following youtube video as inspiration for my Timeline View: [SwiftUI 3.0 - Task Management App UI - Complex UI - MVVM - Xcode 13 - SwiftUI Tutorials](https://www.youtube.com/watch?v=nKHrsrmA4lM&ab_channel=Kavsoft)

I pulled the LinkedIn Icon from their brand package: [LinkedIn Brand Guidelines](https://brand.linkedin.com/downloads)

I pulled the GitHub Icon from their brand package: [GitHub Logos and Usage](https://github.com/logos)

### Related PRs
*Reference the related PRs*

### Testing
I added a few UI tests. There is a unit test for each of the social media buttons. There is also a basic unit test ensuring that the section titles properly renders.

### Reviewer Nudging
*Where should the reviewer start? Where is a good entry point?*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by vishnuravi — APPROVED** [review]
Hi Jennifer! 

This assignment is really well done!  I especially love the timeline that you created! All the checks are passing too 🎉

Feel free to merge this branch into main whenever you're ready. Let us know if you need help resolving any conflicts.

Great job!

Vishnu

**Comment by jennxu23** [comment]
@PSchmiedmayer just pushed! I'm still running into issues because I'm missing Ashley Griffin's member view.

**Comment by PSchmiedmayer** [comment]
@jennxu23 Thank you for pushing your changes, I will take a look at that 👍

**Comment by PSchmiedmayer** [comment]
@jennxu23 I have merged the latest version of the main branch into yours and this should hopefully solve the build issue that you have encountered.

**Pull request merged**
